version: 0.0               # Especifica la versión del formato del archivo.
os: linux                  # Especifica el sistema operativo a usar.
files:                     # Es una lista de archivos para copiar desde el origen al destino.
  - source: /              # Directorio de origen.
    destination: /var/www/html # Directorio de destino.
hooks:                     # Es una lista de scripts que se ejecutan en diferentes puntos del despliegue.
  AfterInstall:            # Script que se ejecuta después de la instalación de la aplicación.
    - location: scripts/install_nginx.sh # Ruta del script a ejecutar.
      timeout: 300         # Tiempo máximo de ejecución del script en segundos.
      runas: root          # Usuario con el que se ejecuta el script.
  ApplicationStart:        # Script que se ejecuta después de iniciar la aplicación.
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root